name: Publish JARs
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "wrapper"
      - name: Build JARs
        uses: Wandalen/wretry.action@master
        with:
          command: "gradle build"
          attempt_limit: 3
      - name: Upload Built JARs
        uses: actions/upload-artifact@v4
        with:
          name: built-jars
          path: |
            ./build/libs/*.jar

  distribute:
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Built JARs
        uses: actions/download-artifact@v4
        with:
          name: built-jars
          path: ./build
      - name: Publish to Modrinth, GitHub.
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: |
            build/libs/*.jar
          version: ${{ github.ref_name }}
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish to Hangar.
        env:
          HANGAR_ID: ${{ vars.HANGAR_ID }}
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
        run: ./gradlew build publishPluginPublicationToHangar --stacktrace
